name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.1
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: gem install bundler
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake
        env:
          DATABASE_URL: postgres://postgres@postgres/postgres
